### PR TITLE
fix: keyring file dir path

### LINKED ISSUE #25: Wrong keyring credentials file dir
### What happened?

The keyring credentials located at `/Users/test/~/.config/pulsar/credentials`

### What did you expect to happen?

Should be `/Users/test/.config/pulsar/credentials`

### PR DESCRIPTION
**Pull request by maxsxu**
Fixes #25 

### Modifications

FileDir is the directory that keyring files are stored in, ~/ is resolved to the users' home dir.

### CODE REVIEW

File: pkg/admin/auth/oauth2.go [hunk 1]
```diff
@@ -243,7 +241,7 @@ func makeKeyring() (keyring.Keyring, error) {
 		ServiceName:              serviceName,
 		KeychainName:             keyChainName,
 		KeychainTrustApplication: true,
-		FileDir:                  filepath.Join(util.HomeDir(), "~/.config/pulsar", "credentials"),
+		FileDir:                  filepath.Join("~/.config/pulsar", "credentials"),
```
Comment (fantapsody) [inline pkg/admin/auth/oauth2.go:244]: Would it be better to use `filepath.Join(util.HomeDir(), ".config/pulsar", "credentials")`?

Comment (maxsxu) [reply pkg/admin/auth/oauth2.go:244]: @fantapsody sorry, I don't think so. Because FileDir in keyring pkg will auto resolve `~/` to the users' home dir. See https://github.com/99designs/keyring/blob/929f178361c0be06c50f0a82598cbfa1a965f40f/config.go#L29

BTW, we should deprecate `util.HomeDir()` in favor of golang builtin `os.UserHomeDir()` as util.HomeDir() doesn't handle error cases.

**Review by fantapsody — APPROVED** [review]
